INSERT INTO forum_ufmg.tags (nome) VALUES
('Introdução à Lógica Computacional'),
('Geometria Analitica e Algebra Linear'),
('Programação e Desenvolvimento de Software I'),
('Fundamentos de Sistemas de Informação'),
('Administração T.G.A.'),
('Programação e Desenvolvimento de Software II'),
('Matemática Discreta'),
('Álgebra Linear Computacional'),
('Economia A I'),
('Cálculo Diferencial e Integral I'),
('Introdução a Banco de Dados'),
('Introdução aos Sistemas Lógicos'),
('Estruturas de Dados'),
('Estatística e Probabilidades'),
('Cálculo Diferencial e Integral II'),
('Usuários da Informação'),
('Organização de Computadores I'),
('Algoritmos I'),
('Administração de Recursos Humanos'),
('Organização e Tratamento Da Informação'),
('Linguagens de Programação'),
('Interação Humano-computador'),
('Introdução à Contabilidade'),
('Administração da Produção'),
('Engenharia de Software'),
('Sistemas Operacionais'),
('Administração de Custos'),
('Engenharia de Software II'),
('Redes de Computadores'),
('Ética na Computação'),
('Administração Financeira'),
('Computação e Sociedade'),
('Administração Mercadológica'),
('Monografia de Sistemas de Informação');
